import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import Sidebar from '@/components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NebulaNook',
  description: 'Generated by Emroze Jawed',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Navbar />
        <div className='flex flex-col md:flex-row'>
          <div className='w-full md:w-1/5'><Sidebar /> </div>
          <div className='md:flex-1' >{children}</div>
        </div>
      </body>
    </html>
  )
}
